### ISSUE TITLE
Como estas

### ISSUE THREAD

**Issue by cookiemonsteruk** [JRGTH/xigmanas-bastille-extension#5]
Disculpa que haga mal uso de esto pero he querido contactarte, si solo para saber como estas. Espero que bien. Que esque no te he visto desde hace mucho tiempo en el foro. Estemos en contacto. Me dices como y te mando my correo electronico o un numero.

**Comment by JRGTH** [comment]
Hola cookiemonster espero te encuentres bien ;), pues e estado un poco ocupado con el trabajo pero todo bien asta el momento, en los "credits page" de XigmaNAS esta my nombre junto a my "gmail", me puedes contactar cuando quieras, de hecho pronto revisare el foro de XigmaNAS para verificar y limpiar los PM's que asumo esta casi lleno.
Saludos cordiales.

**Comment by cookiemonsteruk** [comment]
Me alegra de escuchar. Que cuando vi las noticias de los tornados hace meses me preocupe. Ya busco tu correo y cierro esto para que quede limpio. Saludos.

**Comment by cookiemonsteruk** [comment]
oops, no encuentro el correo en ninguna parte. A lo mejor me das el link cuando puedas

**Comment by tschettervictor** [comment]
English please?

**Comment by tschettervictor** [comment]
> English please?

Never mind. Thanks for the update.

**Comment by JRGTH** [comment]
> oops, no encuentro el correo en ninguna parte. A lo mejor me das el link cuando puedas

Its in ***[Help > License & Credits]*** name "José R....." ;)

Regards

**Comment by cookiemonsteruk** [comment]
> > oops, no encuentro el correo en ninguna parte. A lo mejor me das el link cuando puedas
> 
> Its in _**[Help > License & Credits]**_ name "José R....." ;)
> 
> Regards

Found it. Closing.
